# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market_data.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11market_data.proto\x12\x0bmarket_data\"\x07\n\x05\x45mpty\",\n\x13SubscriptionRequest\x12\x15\n\rinstrument_id\x18\x01 \x01(\x05\"7\n\nInstrument\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x05\"C\n\x13InstrumentsResponse\x12,\n\x0binstruments\x18\x01 \x03(\x0b\x32\x17.market_data.Instrument\"-\n\nPriceLevel\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x10\n\x08quantity\x18\x02 \x01(\x01\"\x8b\x01\n\x11OrderbookSnapshot\x12\x15\n\rinstrument_id\x18\x01 \x01(\x05\x12%\n\x04\x62ids\x18\x02 \x03(\x0b\x32\x17.market_data.PriceLevel\x12%\n\x04\x61sks\x18\x03 \x03(\x0b\x32\x17.market_data.PriceLevel\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\xa6\x01\n\x14OrderbookIncremental\x12\x15\n\rinstrument_id\x18\x01 \x01(\x05\x12,\n\x0bupdate_type\x18\x02 \x01(\x0e\x32\x17.market_data.UpdateType\x12&\n\x05level\x18\x03 \x01(\x0b\x32\x17.market_data.PriceLevel\x12\x0e\n\x06is_bid\x18\x04 \x01(\x08\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"\x89\x01\n\x0fOrderbookUpdate\x12\x32\n\x08snapshot\x18\x01 \x01(\x0b\x32\x1e.market_data.OrderbookSnapshotH\x00\x12\x38\n\x0bincremental\x18\x02 \x01(\x0b\x32!.market_data.OrderbookIncrementalH\x00\x42\x08\n\x06update*.\n\nUpdateType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06REMOVE\x10\x01\x12\x0b\n\x07REPLACE\x10\x02\x32\xb3\x01\n\x11MarketDataService\x12V\n\x12SubscribeOrderbook\x12 .market_data.SubscriptionRequest\x1a\x1c.market_data.OrderbookUpdate0\x01\x12\x46\n\x0eGetInstruments\x12\x12.market_data.Empty\x1a .market_data.InstrumentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPDATETYPE']._serialized_start=713
  _globals['_UPDATETYPE']._serialized_end=759
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=43
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=87
  _globals['_INSTRUMENT']._serialized_start=89
  _globals['_INSTRUMENT']._serialized_end=144
  _globals['_INSTRUMENTSRESPONSE']._serialized_start=146
  _globals['_INSTRUMENTSRESPONSE']._serialized_end=213
  _globals['_PRICELEVEL']._serialized_start=215
  _globals['_PRICELEVEL']._serialized_end=260
  _globals['_ORDERBOOKSNAPSHOT']._serialized_start=263
  _globals['_ORDERBOOKSNAPSHOT']._serialized_end=402
  _globals['_ORDERBOOKINCREMENTAL']._serialized_start=405
  _globals['_ORDERBOOKINCREMENTAL']._serialized_end=571
  _globals['_ORDERBOOKUPDATE']._serialized_start=574
  _globals['_ORDERBOOKUPDATE']._serialized_end=711
  _globals['_MARKETDATASERVICE']._serialized_start=762
  _globals['_MARKETDATASERVICE']._serialized_end=941
# @@protoc_insertion_point(module_scope)
