# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import market_data_pb2 as market__data__pb2


class MarketDataServiceStub(object):
    """Service definition for market data streaming
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeOrderbook = channel.unary_stream(
                '/market_data.MarketDataService/SubscribeOrderbook',
                request_serializer=market__data__pb2.SubscriptionRequest.SerializeToString,
                response_deserializer=market__data__pb2.OrderbookUpdate.FromString,
                )
        self.GetInstruments = channel.unary_unary(
                '/market_data.MarketDataService/GetInstruments',
                request_serializer=market__data__pb2.Empty.SerializeToString,
                response_deserializer=market__data__pb2.InstrumentsResponse.FromString,
                )


class MarketDataServiceServicer(object):
    """Service definition for market data streaming
    """

    def SubscribeOrderbook(self, request, context):
        """Subscribe to orderbook updates for a specific instrument
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstruments(self, request, context):
        """Gret available instruments
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeOrderbook': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeOrderbook,
                    request_deserializer=market__data__pb2.SubscriptionRequest.FromString,
                    response_serializer=market__data__pb2.OrderbookUpdate.SerializeToString,
            ),
            'GetInstruments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstruments,
                    request_deserializer=market__data__pb2.Empty.FromString,
                    response_serializer=market__data__pb2.InstrumentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'market_data.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketDataService(object):
    """Service definition for market data streaming
    """

    @staticmethod
    def SubscribeOrderbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/market_data.MarketDataService/SubscribeOrderbook',
            market__data__pb2.SubscriptionRequest.SerializeToString,
            market__data__pb2.OrderbookUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInstruments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market_data.MarketDataService/GetInstruments',
            market__data__pb2.Empty.SerializeToString,
            market__data__pb2.InstrumentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
